version: '3.6'

services:
  # name of our container
  frontend-dev:
    container_name: frontend
    build:
      context: frontend
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    ports:
      - '8080:8080'

  backend-dev:
    container_name: backend
    build:
      context: backend
      target: dev
    env_file:
      - ./backend/local.env
    volumes:
      - ./backend:/app
    depends_on:
      - 'mongodb-dev'
    ports:
      - '3000:3000'

  mongodb-dev:
    image: 'mongo:4.2.2'
    container_name: mongodb
    env_file:
      - ./mongodb/local.env
    command:
      - '--auth'
    volumes:
      - mongodb:/data/db
    ports:
      - '27017-27019:27017-27019'

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      target: dev
    ports:
      - '8000:8000'

volumes:
  mongodb:
